language: swift
osx_image: xcode11.5

branches:
    only:
    - master

script:
- set -o pipefail && xcodebuild test -project Grid.xcodeproj -scheme 'Grid' -sdk iphonesimulator13.5 ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro' | xcpretty;

notifications:
    slack: exyte:j0jYcgVm6XU9FEKP8WBAiJJj