language: swift
osx_image: xcode12

branches:
    only:
    - master

script:
- set -o pipefail && xcodebuild test -project Grid.xcodeproj -scheme 'Grid' -sdk iphonesimulator14.0 ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro' | xcpretty;

notifications:
    slack: exyte:j0jYcgVm6XU9FEKP8WBAiJJj
